In [5]:
import pandas as pd

In [6]:
train = pd.read_csv("data/train.csv")
test = pd.read_csv("data/test.csv")

In [7]:
train.head()

,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
0,train_0,0,8.9255,-6.7863,11.9081,5.0930,11.4607,-9.2834,5.1187,18.6266,...,4.4354,3.9642,3.1364,1.6910,18.5227,-2.3978,7.8784,8.5635,12.7803,-1.0914
1,train_1,0,11.5006,-4.1473,13.8588,5.3890,12.3622,7.0433,5.6208,16.5338,...,7.6421,7.7214,2.5837,10.9516,15.4305,2.0339,8.1267,8.7889,18.3560,1.9518
2,train_2,0,8.6093,-2.7457,12.0805,7.8928,10.5825,-9.0837,6.9427,14.6155,...,2.9057,9.7905,1.6704,1.6858,21.6042,3.1417,-6.5213,8.2675,14.7222,0.3965
3,train_3,0,11.0604,-2.1518,8.9522,7.1957,12.5846,-1.8361,5.8428,14.9250,...,4.4666,4.7433,0.7178,1.4214,23.0347,-1.2706,-2.9275,10.2922,17.9697,-8.9996
4,train_4,0,9.8369,-1.4834,12.8746,6.6375,12.2772,2.4486,5.9405,19.2514,...,-1.4905,9.5214,-0.1508,9.1942,13.2876,-1.5121,3.9267,9.5031,17.9974,-8.8104

In [8]:
corr = train.corr().abs()
corr

,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,...,var_190,var_191,var_192,var_193,var_194,var_195,var_196,var_197,var_198,var_199
target,1.000000,0.052390,0.050343,0.055870,0.011055,0.010915,0.030979,0.066731,0.003025,0.019584,...,0.055973,0.047114,0.042858,0.017709,0.022838,0.028285,0.023608,0.035303,0.053000,0.025434
var_0,0.052390,1.000000,0.000544,0.006573,0.003801,0.001326,0.003046,0.006983,0.002429,0.004962,...,0.002752,0.000206,0.005373,0.001616,0.001514,0.002073,0.004386,0.000753,0.005776,0.003850
var_1,0.050343,0.000544,1.000000,0.003980,0.000010,0.000303,0.000902,0.003258,0.001511,0.004098,...,0.006627,0.003621,0.002604,0.001153,0.002557,0.000785,0.000377,0.004157,0.004861,0.002287
var_2,0.055870,0.006573,0.003980,1.000000,0.001001,0.000723,0.001569,0.000883,0.000991,0.002648,...,0.000197,0.001285,0.003400,0.000549,0.002104,0.001070,0.003952,0.001078,0.000877,0.003855
var_3,0.011055,0.003801,0.000010,0.001001,1.000000,0.000322,0.003253,0.000774,0.002500,0.003553,...,0.000151,0.002445,0.001530,0.001699,0.001054,0.001206,0.002800,0.001164,0.001651,0.000506
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
var_195,0.028285,0.002073,0.000785,0.001070,0.001206,0.003706,0.001274,0.001244,0.001854,0.001396,...,0.004571,0.000870,0.004745,0.003143,0.001201,1.000000,0.002517,0.004170,0.000536,0.002042
var_196,0.023608,0.004386,0.000377,0.003952,0.002800,0.000513,0.002880,0.005378,0.001045,0.003242,...,0.000847,0.002466,0.001386,0.005308,0.005040,0.002517,1.000000,0.000454,0.000253,0.000607
var_197,0.035303,0.000753,0.004157,0.001078,0.001164,0.000046,0.000535,0.003565,0.003466,0.004583,...,0.004974,0.000906,0.000527,0.005068,0.000884,0.004170,0.000454,1.000000,0.001183,0.004991
var_198,0.053000,0.005776,0.004861,0.000877,0.001651,0.001821,0.000953,0.003025,0.000650,0.002950,...,0.000153,0.000067,0.003451,0.001646,0.003194,0.000536,0.000253,0.001183,1.000000,0.004731
var_199,0.025434,0.003850,0.002287,0.003855,0.000506,0.000786,0.002767,0.006096,0.001457,0.000854,...,0.000404,0.003595,0.001239,0.000552,0.005615,0.002042,0.000607,0.004991,0.004731,1.000000

In [27]:
max(corr["target"][1:])

0.0809173322745462

# maximum correlation is very small